list-procs:
	gcc -Wall -ansi -Wno-format-truncation -std=c99 -o list-procs list-procs.c ../../../lib/error-book.c ../../../lib/get-num.c ../../../ch8-users-groups/chapter-examples/8-1/ugid-functions.c

clean:
	rm -f list-procs
